"""unique for deegre.name

Revision ID: 218e93b57d1f
Revises: 61b2d9cf471d
Create Date: 2023-08-28 18:33:42.721568

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "218e93b57d1f"
down_revision: Union[str, None] = "61b2d9cf471d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "deegres", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "deegres", type_="unique")
    # ### end Alembic commands ###
