"""add table structures

Revision ID: 5b213b801e17
Revises: 218e93b57d1f
Create Date: 2023-08-31 17:10:23.863065

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b213b801e17"
down_revision: Union[str, None] = "218e93b57d1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "structures",
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("structures")
    op.drop_table("deegres")
    # ### end Alembic commands ###
