"""add deegre table

Revision ID: 61b2d9cf471d
Revises: 11e5f3a442cd
Create Date: 2023-08-28 17:52:50.461647

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61b2d9cf471d"
down_revision: Union[str, None] = "11e5f3a442cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deegres",
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="test_pkey"),
    )
    op.drop_table("deegres")
    # ### end Alembic commands ###
