"""Added direction table

Revision ID: 1abb8a452ca0
Revises: 5b213b801e17
Create Date: 2023-12-03 22:27:42.838131

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1abb8a452ca0"
down_revision: Union[str, None] = "5b213b801e17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direction",
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("structure_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["structures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("direction")
    # ### end Alembic commands ###
